Linear regression house price prediction from scratch .

In [ ]:
#import important libraries
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import seaborn as sns
import math
import copy
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)

In [ ]:

(x_train,y_train),(x_test,y_test)=tf.keras.datasets.boston_housing.load_data(path='boston_housing',test_split=0.20,seed=113)

In [ ]:
print(f"X Shape: {x_train.shape}, X Type:{type(x_train)})")
print(x_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (404, 13), X Type:<class 'numpy.ndarray'>)
[[1.23e+00 0.00e+00 8.14e+00 ... 2.10e+01 3.97e+02 1.87e+01]
 [2.18e-02 8.25e+01 2.03e+00 ... 1.47e+01 3.95e+02 3.11e+00]
 [4.90e+00 0.00e+00 1.81e+01 ... 2.02e+01 3.76e+02 3.26e+00]
 ...
 [3.47e-02 3.50e+01 6.06e+00 ... 1.69e+01 3.62e+02 7.83e+00]
 [2.15e+00 0.00e+00 1.96e+01 ... 1.47e+01 2.62e+02 1.58e+01]
 [1.44e-02 6.00e+01 2.93e+00 ... 1.56e+01 3.77e+02 4.38e+00]]
y Shape: (404,), y Type:<class 'numpy.ndarray'>)
[15.2 42.3 50.  21.1 17.7 18.5 11.3 15.6 15.6 14.4 12.1 17.9 23.1 19.9
 15.7  8.8 50.  22.5 24.1 27.5 10.9 30.8 32.9 24.  18.5 13.3 22.9 34.7
 16.6 17.5 22.3 16.1 14.9 23.1 34.9 25.  13.9 13.1 20.4 20.  15.2 24.7
 22.2 16.7 12.7 15.6 18.4 21.  30.1 15.1 18.7  9.6 31.5 24.8 19.1 22.
 14.5 11.  32.  29.4 20.3 24.4 14.6 19.5 14.1 14.3 15.6 10.5  6.3 19.3
 19.3 13.4 36.4 17.8 13.5 16.5  8.3 14.3 16.  13.4 28.6 43.5 20.2 22.
 23.  20.7 12.5 48.5 14.6 13.4 23.7 50.  21.7 39.8 38.7 22.2 34.9 22.5
 31.1 28.7 46.  41.7 21.  26.6 1

In [ ]:

#intialize bias and weight
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618,0.49133566,-54.46734522,-27.10330853,19.45892301,50.34213011,0.42101322,20.10156332,23.14588212,-28.54271241])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (13,), b_init type: <class 'float'>


In [ ]:
#fun to predict single loop
def predict_single_loop(x, w, b):

    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]
        p = p + p_i
    p = p + b
    return p

In [ ]:

#check x vector shape
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

x_vec shape (13,), x_vec value: [  1.23   0.     8.14   0.     0.54   6.14  91.7    3.98   4.   307.
  21.   396.9   18.72]


In [ ]:
#check shape of predict single loop
f_wb = predict_single_loop(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

f_wb shape (), prediction: 7014.0825529781305


In [ ]:
# prediction fun
def predict(x_test, w, b):
    p = np.dot(x_test, w) + b
    return p

In [ ]:
#check shape of x vector
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")

x_vec shape (13,), x_vec value: [  1.23   0.     8.14   0.     0.54   6.14  91.7    3.98   4.   307.
  21.   396.9   18.72]


In [ ]:
#check shape of prediction
f_wb = predict(x_vec,w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

f_wb shape (), prediction: 7014.0825529781305


In [ ]:
#cost fun
def compute_cost(x, y, w, b):
    m = x.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(x[i], w) + b
        cost = cost + (f_wb_i - y[i])**2
    cost = cost / (2 * m)
    return cost

In [ ]:

#print cost
cost = compute_cost(x_train, y_train, w_init, b_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : 29031556.49724754


In [ ]:

# fun to find gradient
def compute_gradient(x, y, w, b):

    m,n = x.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range(m):
        err = (np.dot(x[i], w) + b) - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * x[i, j]
        dj_db = dj_db + err
    dj_dw = dj_dw / m
    dj_db = dj_db / m

    return dj_db, dj_dw

In [ ]:

#call fun of gradient
tmp_dj_db, tmp_dj_dw = compute_gradient(x_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: 7112.321522671282
dj_dw at initial w,b: 
 [1.64e+04 1.14e+05 6.73e+04 4.29e+02 3.76e+03 4.51e+04 4.42e+05 2.99e+04
 5.56e+04 2.65e+06 1.30e+05 2.75e+06 7.91e+04]


In [ ]:
# fun to find gradient descent
def gradient_descent(x, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):
    J_history = []
    w = copy.deepcopy(w_in)
    b = b_in

    for i in range(num_iters):


        dj_db,dj_dw = gradient_function(x, y, w, b)


        w = w - alpha * dj_dw
        b = b - alpha * dj_db

        if i<50:
            J_history.append( cost_function(x, y, w, b))

        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")

    return w, b, J_history

In [ ]:
#prediction to check the accuracy
initial_w = np.zeros_like(w_init)
initial_b = 0.
iterations = 11000
alpha = 5.0e-7

w_final, b_final, J_hist = gradient_descent(x_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient,
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m, _ = x_train.shape
for i in range(m):
    a = np.dot(x_train[i], w_final) + b_final
    b = y_train[i]
    sum = a-b
    print(f"prediction: {a}, target value: {b}")

Iteration    0: Cost   227.92   
Iteration 1100: Cost    48.30   
Iteration 2200: Cost    48.30   
Iteration 3300: Cost    48.30   
Iteration 4400: Cost    48.30   
Iteration 5500: Cost    48.30   
Iteration 6600: Cost    48.30   
Iteration 7700: Cost    48.30   
Iteration 8800: Cost    48.30   
Iteration 9900: Cost    48.30   
b,w found by gradient descent: 0.00,[-0.04  0.13 -0.03  0.    0.    0.04  0.05  0.01 -0.    0.    0.02  0.05
 -0.12] 
prediction: 22.83897736357193, target value: 15.2
prediction: 31.866294485633404, target value: 42.3
prediction: 24.308818656915232, target value: 50.0
prediction: 21.353079478623446, target value: 21.1
prediction: 23.349263013107112, target value: 17.7
prediction: 22.528162698361328, target value: 18.5
prediction: 22.826962655873576, target value: 11.3
prediction: 21.939757636171276, target value: 15.6
prediction: 11.991117946867588, target value: 15.6
prediction: 21.289261228446385, target value: 14.4
prediction: 22.20423889885148, target value

In [ ]:
#show how out of our model is near to out of target
print((np.mean(sum))**2)

1.6357621948999517
