deep neural network classification

import important libraries

In [1]:
import numpy as np
import matplotlib as plt
import pandas as pd
import tensorflow as tf
import math

from tensorflow import keras
from keras.utils import normalize,to_categorical
from tensorflow.keras.layers import Flatten,Dense
from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,classification_report

load dataset

In [4]:
x_train=pd.read_csv('/content/optdigits.tra')

split dataset

In [5]:
x=x_train.iloc[:,:-1].values
y=x_train.iloc[:,-1].values

one hot encoding

In [6]:
y_train=to_categorical(y)

In [7]:
print(y)

[0 7 4 ... 6 6 7]


In [8]:
print(y_train)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


train test split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

to catigorical to convert class to binary class

In [10]:
nb_classes = 10

y_train = to_categorical(y_train, nb_classes)
y_test = to_categorical(y_test, nb_classes)

build our model

In [11]:
model = tf.keras.Sequential()
model.add(Dense(128, input_shape=(64,), activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation = "softmax"))
opt = tf.keras.optimizers.Adam(learning_rate=1e-2)



compile model

In [12]:
model.compile(optimizer = opt, loss = 'categorical_crossentropy', metrics=['acc'])

fit model

In [13]:
history = model.fit(x_train,y_train, epochs=50, batch_size=128, validation_split = 0.2)

Epoch 1/50
20/20 [==============================] - 1s 16ms/step - loss: 1.5854 - acc: 0.6429 - val_loss: 0.4270 - val_acc: 0.8889
Epoch 2/50
20/20 [==============================] - 0s 6ms/step - loss: 0.2711 - acc: 0.9219 - val_loss: 0.2397 - val_acc: 0.9297
Epoch 3/50
20/20 [==============================] - 0s 6ms/step - loss: 0.1506 - acc: 0.9542 - val_loss: 0.1955 - val_acc: 0.9477
Epoch 4/50
20/20 [==============================] - 0s 5ms/step - loss: 0.0994 - acc: 0.9693 - val_loss: 0.1249 - val_acc: 0.9739
Epoch 5/50
20/20 [==============================] - 0s 5ms/step - loss: 0.0502 - acc: 0.9853 - val_loss: 0.1210 - val_acc: 0.9673
Epoch 6/50
20/20 [==============================] - 0s 6ms/step - loss: 0.0453 - acc: 0.9849 - val_loss: 0.1187 - val_acc: 0.9739
Epoch 7/50
20/20 [==============================] - 0s 6ms/step - loss: 0.0456 - acc: 0.9845 - val_loss: 0.1109 - val_acc: 0.9739
Epoch 8/50
20/20 [==============================] - 0s 5ms/step - loss: 0.0641 - acc: 0.9

Accuracy

In [14]:
loss,accuracy=model.evaluate(x_train,y_train)
print('model_loss=%.2f,model_accuracy=%.2f' % (loss*100,accuracy*100))

96/96 [==============================] - 0s 1ms/step - loss: 0.0236 - acc: 0.9967
model_loss=2.36,model_accuracy=99.67


In [15]:
loss,accuracy=model.evaluate(x_test,y_test)

print('model_loss=%.2f,model_accuracy=%.2f' % (loss*100,accuracy*100))

24/24 [==============================] - 0s 2ms/step - loss: 0.0920 - acc: 0.9869
model_loss=9.20,model_accuracy=98.69
